CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL,
  user_password TEXT NOT NULL
);

CREATE TABLE entries (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  mood TEXT NOT NULL,
  "description" TEXT NOT NULL,
  modified TIMESTAMPTZ default now() NOT NULL,
  author INTEGER REFERENCES users(id)
);


--seed
INSERT INTO users (user_name, user_password)
VALUES
  ('DemoUser', 'Password1234');

INSERT INTO entries (title, mood, "description", author)
VALUES
  ('First day of work', 'excited', 'I am excited because here are the reasons. Here is what happened and why.', 1),
  ('Rainy day', 'sad', 'I am excited because here are the reasons. Here is what happened and why.', 1),
  ('App not working', 'frustrated', 'I am excited because here are the reasons. Here is what happened and why.', 1),
  ('social justice', 'anxious', 'I am excited because here are the reasons. Here is what happened and why.', 1);
